---
apiVersion: v1
kind: Template
metadata:
  name: io-gathering-conditions
objects:

- kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v1
  metadata:
    labels:
      app: io-gathering-conditions
    name: io-gathering-conditions
  spec:
    minReplicas: ${{MIN_REPLICAS}}
    maxReplicas: ${{MAX_REPLICAS}}
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: io-gathering-conditions-service
    targetCPUUtilizationPercentage: 50

- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: io-gathering-conditions
  spec:
    envName: ${ENV_NAME}
    testing:
      iqePlugin: ccx
    dependencies:
      - ingress
    deployments:
      - name: service
        minReplicas: ${{MIN_REPLICAS}}
        webServices:
          public:
            enabled: true
          private:
            enabled: false
          metrics:
            enabled: true
        podSpec:
          env:
            - name: INSIGHTS_OPERATOR_CONDITIONAL_SERVICE_CONFIG_FILE
              value: /data/config.toml
          image: ${IMAGE}:${IMAGE_TAG}
          volumeMounts:
            - mountPath: /data
              name: io-gathering-conditions-config
          volumes:
            - configMap:
                name: io-gathering-conditions-config-map
              name: io-gathering-conditions-config
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi

- kind: ConfigMap
  apiVersion: v1
  metadata:
    labels:
      app: io-gathering-conditions
    name: io-gathering-conditions-config-map
  data:
    config.toml: |-
      [server]
      address = ":8081"
      use_https = false
      enable_cors = false

      [storage]
      rules_path = "/conditions"

parameters:
- description: Image name
  name: IMAGE
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: ClowdEnv Name
  name: ENV_NAME
  requred: true
- description: Minimum number of pods to use when autoscaling is enabled
  name: MIN_REPLICAS
  value: '1'
- description: Minimum number of pods to use when autoscaling is enabled
  name: MAX_REPLICAS
  value: '1'
